[package]
name = "a-lisp-interpreter"
version = "0.1.0"
authors = ["Matthias Drescher <matthias_p_drescher@t-online.de>"]

[lib]
name = "alisplib"
path = "lib/lib.rs"

[[bin]]
name = "ali"
path = "src/main.rs"

[[bin]]
name = "doctool"
path = "doctool/main.rs"

[dependencies]
rustyline = "*"
